#ifndef PROTOTEST_H
#define PROTOTEST_H

// CreateDOM: Schema Generation tool written by John W. Ratcliff, 2017
// Warning:This source file was auto-generated by the CreateDOM tool. Do not try to edit this source file manually!
// The Google DOCs Schema Spreadsheet for this source came from: https://docs.google.com/spreadsheets/d/1GqDdgpCI4n5tPY2xw2BaLjz2PHIcIAZqQ65Xe48nuf4/edit?usp=sharing

#include <stdint.h>
#include <vector>


namespace PROTO_TEST
{


// Defines the physical material properties of a surface
class PhysicsMaterial
{
public:
	bool 		disableFriction{ false }; 							// If true, then friction is disabled for the material
	bool 		disableStrongFriction{ false };   					// If true then strong friction is disabled for the material
	float  		dynamicFriction{ 0.5f };  							// The coefficient of dynamic friction.
	float  		staticFriction{ 0.5f }; 							// The coefficient of static friction
};



} // End of PROTO_TEST namespace

#endif // End of PROTOTEST_H
