#ifndef PROTOADDRESSBOOK_H
#define PROTOADDRESSBOOK_H

// CreateDOM: Schema Generation tool written by John W. Ratcliff, 2017
// Warning:This source file was auto-generated by the CreateDOM tool. Do not try to edit this source file manually!
// The Google DOCs Schema Spreadsheet for this source came from: https://docs.google.com/spreadsheets/d/1lGtmCRvTVFmXY9zNneUJsdQiEOAovg6dIj766xpQFbM/edit?usp=sharing

#include <stdint.h>
#include <vector>


namespace PROTO_ADDRESS_BOOK
{


enum PhoneType
{
	MOBILE,								// This is a mobile/cell phone number
	HOME,  								// This is a person's home telephone number
	WORK,  								// This is the person's work phone
};


class PhoneNumber
{
public:
	std::string	number;											// Phone number 
	PhoneType  	type;  											// Type of phone number
};


// Defines an address and phone number for a person
class Person
{
public:
	std::string	name;  											// Name of person
	int32_t		id{ 0 };  											// Unique id of person
	std::string	email;   										// Email address of person
};



} // End of PROTO_ADDRESS_BOOK namespace

#endif // End of PROTOADDRESSBOOK_H
